//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Database1Model", "FK_Guesses_Games", "Game", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(TriviaGame.Game), "Guess", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TriviaGame.Guess), true)]
[assembly: EdmRelationshipAttribute("Database1Model", "FK_Answers_Questions", "Question", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TriviaGame.Question), "Answer", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TriviaGame.Answer), true)]
[assembly: EdmRelationshipAttribute("Database1Model", "FK_Guesses_Answers", "Answer", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TriviaGame.Answer), "Guess", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TriviaGame.Guess), true)]

#endregion

namespace TriviaGame
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Trivia : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Trivia object using the connection string found in the 'Trivia' section of the application configuration file.
        /// </summary>
        public Trivia() : base("name=Trivia", "Trivia")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Trivia object.
        /// </summary>
        public Trivia(string connectionString) : base(connectionString, "Trivia")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Trivia object.
        /// </summary>
        public Trivia(EntityConnection connection) : base(connection, "Trivia")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Answer> Answers
        {
            get
            {
                if ((_Answers == null))
                {
                    _Answers = base.CreateObjectSet<Answer>("Answers");
                }
                return _Answers;
            }
        }
        private ObjectSet<Answer> _Answers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Question> Questions
        {
            get
            {
                if ((_Questions == null))
                {
                    _Questions = base.CreateObjectSet<Question>("Questions");
                }
                return _Questions;
            }
        }
        private ObjectSet<Question> _Questions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Guess> Guesses
        {
            get
            {
                if ((_Guesses == null))
                {
                    _Guesses = base.CreateObjectSet<Guess>("Guesses");
                }
                return _Guesses;
            }
        }
        private ObjectSet<Guess> _Guesses;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Game> Games
        {
            get
            {
                if ((_Games == null))
                {
                    _Games = base.CreateObjectSet<Game>("Games");
                }
                return _Games;
            }
        }
        private ObjectSet<Game> _Games;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Answers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAnswers(Answer answer)
        {
            base.AddObject("Answers", answer);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Questions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToQuestions(Question question)
        {
            base.AddObject("Questions", question);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Guesses EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGuesses(Guess guess)
        {
            base.AddObject("Guesses", guess);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Games EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGames(Game game)
        {
            base.AddObject("Games", game);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Database1Model", Name="Answer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Answer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Answer object.
        /// </summary>
        /// <param name="ansID">Initial value of the AnsID property.</param>
        /// <param name="ansQueID">Initial value of the AnsQueID property.</param>
        /// <param name="ansCorrect">Initial value of the AnsCorrect property.</param>
        /// <param name="ansInactive">Initial value of the AnsInactive property.</param>
        public static Answer CreateAnswer(global::System.Int32 ansID, global::System.Int32 ansQueID, global::System.Boolean ansCorrect, global::System.Boolean ansInactive)
        {
            Answer answer = new Answer();
            answer.AnsID = ansID;
            answer.AnsQueID = ansQueID;
            answer.AnsCorrect = ansCorrect;
            answer.AnsInactive = ansInactive;
            return answer;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AnsID
        {
            get
            {
                return _AnsID;
            }
            set
            {
                if (_AnsID != value)
                {
                    OnAnsIDChanging(value);
                    ReportPropertyChanging("AnsID");
                    _AnsID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AnsID");
                    OnAnsIDChanged();
                }
            }
        }
        private global::System.Int32 _AnsID;
        partial void OnAnsIDChanging(global::System.Int32 value);
        partial void OnAnsIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AnsQueID
        {
            get
            {
                return _AnsQueID;
            }
            set
            {
                OnAnsQueIDChanging(value);
                ReportPropertyChanging("AnsQueID");
                _AnsQueID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AnsQueID");
                OnAnsQueIDChanged();
            }
        }
        private global::System.Int32 _AnsQueID;
        partial void OnAnsQueIDChanging(global::System.Int32 value);
        partial void OnAnsQueIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AnsImagePath
        {
            get
            {
                return _AnsImagePath;
            }
            set
            {
                OnAnsImagePathChanging(value);
                ReportPropertyChanging("AnsImagePath");
                _AnsImagePath = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AnsImagePath");
                OnAnsImagePathChanged();
            }
        }
        private global::System.String _AnsImagePath;
        partial void OnAnsImagePathChanging(global::System.String value);
        partial void OnAnsImagePathChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean AnsCorrect
        {
            get
            {
                return _AnsCorrect;
            }
            set
            {
                OnAnsCorrectChanging(value);
                ReportPropertyChanging("AnsCorrect");
                _AnsCorrect = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AnsCorrect");
                OnAnsCorrectChanged();
            }
        }
        private global::System.Boolean _AnsCorrect;
        partial void OnAnsCorrectChanging(global::System.Boolean value);
        partial void OnAnsCorrectChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean AnsInactive
        {
            get
            {
                return _AnsInactive;
            }
            set
            {
                OnAnsInactiveChanging(value);
                ReportPropertyChanging("AnsInactive");
                _AnsInactive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AnsInactive");
                OnAnsInactiveChanged();
            }
        }
        private global::System.Boolean _AnsInactive;
        partial void OnAnsInactiveChanging(global::System.Boolean value);
        partial void OnAnsInactiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AnsText
        {
            get
            {
                return _AnsText;
            }
            set
            {
                OnAnsTextChanging(value);
                ReportPropertyChanging("AnsText");
                _AnsText = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AnsText");
                OnAnsTextChanged();
            }
        }
        private global::System.String _AnsText;
        partial void OnAnsTextChanging(global::System.String value);
        partial void OnAnsTextChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Database1Model", "FK_Answers_Questions", "Question")]
        public Question Question
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Question>("Database1Model.FK_Answers_Questions", "Question").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Question>("Database1Model.FK_Answers_Questions", "Question").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Question> QuestionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Question>("Database1Model.FK_Answers_Questions", "Question");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Question>("Database1Model.FK_Answers_Questions", "Question", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Database1Model", "FK_Guesses_Answers", "Guess")]
        public EntityCollection<Guess> Guesses
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Guess>("Database1Model.FK_Guesses_Answers", "Guess");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Guess>("Database1Model.FK_Guesses_Answers", "Guess", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Database1Model", Name="Game")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Game : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Game object.
        /// </summary>
        /// <param name="gamID">Initial value of the GamID property.</param>
        /// <param name="gamDifficulty">Initial value of the GamDifficulty property.</param>
        public static Game CreateGame(global::System.Int32 gamID, global::System.Int32 gamDifficulty)
        {
            Game game = new Game();
            game.GamID = gamID;
            game.GamDifficulty = gamDifficulty;
            return game;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GamID
        {
            get
            {
                return _GamID;
            }
            set
            {
                if (_GamID != value)
                {
                    OnGamIDChanging(value);
                    ReportPropertyChanging("GamID");
                    _GamID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("GamID");
                    OnGamIDChanged();
                }
            }
        }
        private global::System.Int32 _GamID;
        partial void OnGamIDChanging(global::System.Int32 value);
        partial void OnGamIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GamPlayerName
        {
            get
            {
                return _GamPlayerName;
            }
            set
            {
                OnGamPlayerNameChanging(value);
                ReportPropertyChanging("GamPlayerName");
                _GamPlayerName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GamPlayerName");
                OnGamPlayerNameChanged();
            }
        }
        private global::System.String _GamPlayerName;
        partial void OnGamPlayerNameChanging(global::System.String value);
        partial void OnGamPlayerNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> GamScore
        {
            get
            {
                return _GamScore;
            }
            set
            {
                OnGamScoreChanging(value);
                ReportPropertyChanging("GamScore");
                _GamScore = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GamScore");
                OnGamScoreChanged();
            }
        }
        private Nullable<global::System.Int32> _GamScore;
        partial void OnGamScoreChanging(Nullable<global::System.Int32> value);
        partial void OnGamScoreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> GamDateTime
        {
            get
            {
                return _GamDateTime;
            }
            set
            {
                OnGamDateTimeChanging(value);
                ReportPropertyChanging("GamDateTime");
                _GamDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GamDateTime");
                OnGamDateTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _GamDateTime;
        partial void OnGamDateTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnGamDateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GamDifficulty
        {
            get
            {
                return _GamDifficulty;
            }
            set
            {
                OnGamDifficultyChanging(value);
                ReportPropertyChanging("GamDifficulty");
                _GamDifficulty = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GamDifficulty");
                OnGamDifficultyChanged();
            }
        }
        private global::System.Int32 _GamDifficulty;
        partial void OnGamDifficultyChanging(global::System.Int32 value);
        partial void OnGamDifficultyChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Database1Model", "FK_Guesses_Games", "Guess")]
        public EntityCollection<Guess> Guesses
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Guess>("Database1Model.FK_Guesses_Games", "Guess");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Guess>("Database1Model.FK_Guesses_Games", "Guess", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Database1Model", Name="Guess")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Guess : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Guess object.
        /// </summary>
        /// <param name="gueID">Initial value of the GueID property.</param>
        /// <param name="gueAnsID">Initial value of the GueAnsID property.</param>
        public static Guess CreateGuess(global::System.Int32 gueID, global::System.Int32 gueAnsID)
        {
            Guess guess = new Guess();
            guess.GueID = gueID;
            guess.GueAnsID = gueAnsID;
            return guess;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GueID
        {
            get
            {
                return _GueID;
            }
            set
            {
                if (_GueID != value)
                {
                    OnGueIDChanging(value);
                    ReportPropertyChanging("GueID");
                    _GueID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("GueID");
                    OnGueIDChanged();
                }
            }
        }
        private global::System.Int32 _GueID;
        partial void OnGueIDChanging(global::System.Int32 value);
        partial void OnGueIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GueAnsID
        {
            get
            {
                return _GueAnsID;
            }
            set
            {
                OnGueAnsIDChanging(value);
                ReportPropertyChanging("GueAnsID");
                _GueAnsID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GueAnsID");
                OnGueAnsIDChanged();
            }
        }
        private global::System.Int32 _GueAnsID;
        partial void OnGueAnsIDChanging(global::System.Int32 value);
        partial void OnGueAnsIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> GueGamID
        {
            get
            {
                return _GueGamID;
            }
            set
            {
                OnGueGamIDChanging(value);
                ReportPropertyChanging("GueGamID");
                _GueGamID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GueGamID");
                OnGueGamIDChanged();
            }
        }
        private Nullable<global::System.Int32> _GueGamID;
        partial void OnGueGamIDChanging(Nullable<global::System.Int32> value);
        partial void OnGueGamIDChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Database1Model", "FK_Guesses_Games", "Game")]
        public Game Game
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Game>("Database1Model.FK_Guesses_Games", "Game").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Game>("Database1Model.FK_Guesses_Games", "Game").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Game> GameReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Game>("Database1Model.FK_Guesses_Games", "Game");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Game>("Database1Model.FK_Guesses_Games", "Game", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Database1Model", "FK_Guesses_Answers", "Answer")]
        public Answer Answer
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Answer>("Database1Model.FK_Guesses_Answers", "Answer").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Answer>("Database1Model.FK_Guesses_Answers", "Answer").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Answer> AnswerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Answer>("Database1Model.FK_Guesses_Answers", "Answer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Answer>("Database1Model.FK_Guesses_Answers", "Answer", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Database1Model", Name="Question")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Question : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Question object.
        /// </summary>
        /// <param name="queID">Initial value of the QueID property.</param>
        /// <param name="queQuestion">Initial value of the QueQuestion property.</param>
        /// <param name="queInactive">Initial value of the QueInactive property.</param>
        /// <param name="queDifficulty">Initial value of the QueDifficulty property.</param>
        public static Question CreateQuestion(global::System.Int32 queID, global::System.String queQuestion, global::System.Boolean queInactive, global::System.Int32 queDifficulty)
        {
            Question question = new Question();
            question.QueID = queID;
            question.QueQuestion = queQuestion;
            question.QueInactive = queInactive;
            question.QueDifficulty = queDifficulty;
            return question;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 QueID
        {
            get
            {
                return _QueID;
            }
            set
            {
                if (_QueID != value)
                {
                    OnQueIDChanging(value);
                    ReportPropertyChanging("QueID");
                    _QueID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("QueID");
                    OnQueIDChanged();
                }
            }
        }
        private global::System.Int32 _QueID;
        partial void OnQueIDChanging(global::System.Int32 value);
        partial void OnQueIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String QueQuestion
        {
            get
            {
                return _QueQuestion;
            }
            set
            {
                OnQueQuestionChanging(value);
                ReportPropertyChanging("QueQuestion");
                _QueQuestion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("QueQuestion");
                OnQueQuestionChanged();
            }
        }
        private global::System.String _QueQuestion;
        partial void OnQueQuestionChanging(global::System.String value);
        partial void OnQueQuestionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> QueDropSpeed
        {
            get
            {
                return _QueDropSpeed;
            }
            set
            {
                OnQueDropSpeedChanging(value);
                ReportPropertyChanging("QueDropSpeed");
                _QueDropSpeed = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("QueDropSpeed");
                OnQueDropSpeedChanged();
            }
        }
        private Nullable<global::System.Int32> _QueDropSpeed;
        partial void OnQueDropSpeedChanging(Nullable<global::System.Int32> value);
        partial void OnQueDropSpeedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean QueInactive
        {
            get
            {
                return _QueInactive;
            }
            set
            {
                OnQueInactiveChanging(value);
                ReportPropertyChanging("QueInactive");
                _QueInactive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("QueInactive");
                OnQueInactiveChanged();
            }
        }
        private global::System.Boolean _QueInactive;
        partial void OnQueInactiveChanging(global::System.Boolean value);
        partial void OnQueInactiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 QueDifficulty
        {
            get
            {
                return _QueDifficulty;
            }
            set
            {
                OnQueDifficultyChanging(value);
                ReportPropertyChanging("QueDifficulty");
                _QueDifficulty = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("QueDifficulty");
                OnQueDifficultyChanged();
            }
        }
        private global::System.Int32 _QueDifficulty;
        partial void OnQueDifficultyChanging(global::System.Int32 value);
        partial void OnQueDifficultyChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Database1Model", "FK_Answers_Questions", "Answer")]
        public EntityCollection<Answer> Answers
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Answer>("Database1Model.FK_Answers_Questions", "Answer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Answer>("Database1Model.FK_Answers_Questions", "Answer", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
